Shi-553/RampageCars

Assets/Fields.meta, Assets/Fields/SpringBoard.prefab, Assets/Fields/SpringBoard.prefab.meta, Assets/Scenes/SampleScene.unity, Assets/SpringBoard.meta, Assets/SpringBoard/CreatePolygonMesh.cs, Assets/SpringBoard/CreatePolygonMesh.cs.meta
* https://github.com/Shi-553/RampageCars/issues/11
* ジャンプ台を制作
* とくにないです
* 頂いた参考画像とは少し違います、すみません
=> 張りぼてですが問題なく飛べるかなという坂を作りました。余計なところ触ってたらすみません。

.github/auto_assign.yml, .github/workflows/AutoAssignReviewr.yml
* close #35 
* レビュワーを決めるactionを作った。
* 決める・決めないなどの制御はできない。
=> Add auto assign reviewr

Assets/Cars/QuitGame.cs, Assets/Cars/QuitGame.cs.meta, Assets/Scenes/SampleScene.unity, ProjectSettings/TimelineSettings.asset
* close https://github.com/Shi-553/RampageCars/issues/31
* エンドボタンの追加（コントローラーはBackボタン、キーボードはLキー）
* アプリケーション上で押すとアプリを終了するようにした。
* UnityEditor上で実行した場合Debugが終了するようにした。
* 
* 遅くなってごめんなさい。
=> エンドボタンの追加（コントローラーはBackボタン、キーボードはLキー）

Assets/Scenes/SampleScene.unity
=> カメラリセットできるようにした。

Assets/Audio/BGMManager.cs, Assets/Audio/BGMManager.cs.meta, Assets/Audio/BGMSource.prefab, Assets/Audio/BGMSource.prefab.meta, Assets/Audio/HitAudio.cs, Assets/Audio/MasterMix.mixer, Assets/Audio/MasterMix.mixer.meta, Assets/Audio/SEManager.cs, Assets/Audio/SEManager.cs.meta, Assets/Audio/SESource.prefab, Assets/Audio/SESource.prefab.meta, Assets/Audio/SoundManager.cs, Assets/Audio/SoundManager.cs.meta, Assets/C#/Singleton.cs, Assets/C#/Singleton.cs.meta, Assets/Effects/Script/ContactEffect.cs, Assets/Scenes/Manager.unity, Assets/Scenes/Manager.unity.meta, ProjectSettings/EditorBuildSettings.asset
* close #28 
* マネージャーシーンを勝手に追加読み込みするシングルトンの仕組みを作った。
* 自作オーディオマネージャーを作った。
* `AudioSource`のプレハブと`AudioMixer`で調整できるようにした。
* SEがうるさいときは`AudioMixer`のコンプレッサーで小さくなるようにした。
=> オーディオマネージャーを作った。

Assets/C#/EditorScripts/Editor/RefreshOnPlay.cs
* なし
* ショートカットの変更
* 自動ロックするか選べるようにした
* 緊急なのでNoReview
=> 自動コンパイルロックの調整

Assets/C#/EditorScripts/NotNull/Editor/DisallowPlayModeIfNull.cs, Assets/C#/EditorScripts/NotNull/Editor/NotNullDrawer.cs, Assets/C#/EditorScripts/NotNull/NotNullAttribute.cs, Assets/C#/EditorScripts/SerializeInterface.meta, Assets/C#/EditorScripts/SerializeInterface/Editor.meta, Assets/C#/EditorScripts/SerializeInterface/Editor/SerializeInterfaceDrawer.cs, Assets/C#/EditorScripts/SerializeInterface/Editor/SerializeInterfaceDrawer.cs.meta, Assets/C#/EditorScripts/SerializeInterface/SerializeInterface.cs, Assets/C#/EditorScripts/SerializeInterface/SerializeInterface.cs.meta, Assets/C#/EditorScripts/SerializedPropertyUtility.cs, Assets/C#/EditorScripts/SerializedPropertyUtility.cs.meta
* なし
* `SerializeInterface<T>`を作った。Tをジェネリックインターフェースにできる。
* まだシーンで使って無くて変更点のテストが難しいので NoReview
=> ジェネリックインターフェースをインスペクターで使うためのラッパークラスを作った。

Assets/C#/Debug/DrawBoxCast.cs, Assets/C#/Debug/DrawBoxCast.cs.meta, Assets/Objects/Enemys/TestEnemy.cs, Assets/Objects/Player/IPlayerAction.cs, Assets/Objects/Player/Player.prefab, Assets/Objects/Player/PlayerAction/AccelPlayerAction.cs, Assets/Objects/Player/PlayerAction/DefaultPlayerAction.cs, Assets/Objects/Player/PlayerAction/DriftPlayerActionBase.cs, Assets/Objects/Player/PlayerAction/WiperPlayerAction.cs, Assets/Objects/Player/PlayerAction/WiperPlayerAction.cs.meta, Assets/Objects/Player/PlayerActionManager.cs, Assets/Objects/Player/PlayerController.cs, Assets/Objects/Player/RotateLimit.cs
* close #67 
* ワイパーアクションの追加。
* ノックバックを追加。
* 勝手にノックバック追加したのでプランナーに見てもらいたい。
=> プレイヤーアクション「ワイパー」を追加

Assets/Objects/Player/Player.prefab, Assets/Objects/Player/PlayerAction/DivePlayerAction.cs, Assets/Objects/Player/PlayerAction/DivePlayerAction.cs.meta, Assets/Objects/Player/PlayerController.cs, Assets/Objects/Player/dive.prefab, Assets/Objects/Player/dive.prefab.meta, Assets/Scenes/SampleScene.unity, ProjectSettings/TagManager.asset
* https://github.com/Shi-553/RampageCars/issues/66
* DivePlayerActionスクリプトの作成
* 仮の衝撃波(当たり判定)の作成
* 
* ダイブ時に落下速度を上げようとしたのですが、挙動がバグったので一旦実装は見送りました。
=> プレイヤーアクション「ダイブ」追加

Assets/C#/EditorScripts/Editor/SerializedPropertyUtility.cs, Assets/Objects/Player/PlayerCore.cs, Assets/Objects/Player/PlayerCore.cs.meta, Assets/Scenes/SampleScene.unity
* close #62 （マージしたら自動で閉じる場合closeを付ける）
* HPバーを追加しました
* 何か問題があったら変更します
* レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）
=> Add hit point

Assets/Objects/Player/PlayerActionManager.cs, Assets/Objects/Player/PlayerController.cs
* close #92 
* 前の動作をキャンセルできるようにした。
=> プレイヤーのアクションをキャンセルできるようにする。

Assets/Objects/Player/PlayerFall.cs
* close #99（マージしたら自動で閉じる場合closeを付ける）
* リスポーンの処理にスピードを0にするコードを追加
* 
* どんなスピードで落ちても大丈夫だと思います、不具合があればすぐ対応します。
=> プレイヤーが連続して海に落ちないように

Assets/C#/Debug/QuitGame.cs, Assets/C#/Debug/ResetGame.cs, Assets/Objects/Title.meta, Assets/Objects/Title/タイトル.bmp.meta, Assets/Scenes/ChangeSceneReceiver.cs, Assets/Scenes/ChangeSceneReceiver.cs.meta, Assets/Scenes/Editor/SceneEnumGenerator.cs, Assets/Scenes/GameOver.unity, Assets/Scenes/GameTitle.unity, Assets/Scenes/GameTitle.unity.meta, Assets/Scenes/Manager.unity, Assets/Scenes/QuitReceiver.cs, Assets/Scenes/QuitReceiver.cs.meta, Assets/Scenes/SceneLoader.cs, Assets/Scenes/SceneType.cs, ProjectSettings/EditorBuildSettings.asset
* close #97
* タイトルシーンを作った
* レイアウトはあとで調整予定。
=> 97 ゲームタイトル画面の追加

Assets/Objects/Enemys/TestEnemySponer.cs
なし
* スポーン位置と範囲を調整できるようにした。
* 可視化した。
* 急ぐためレビューしない。NoReview
=> スポーン位置と範囲を調整できるようにした。

Assets/Objects/Enemys/TestEnemy.prefab, Assets/Objects/Enemys/TestEnemyAttacker.cs
* close #110 
* 敵の攻撃を中断させるようにして解決しました
* 髭にはもとからダメージいかなかったみたい
* レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）
=> ワイパーで敵の攻撃を中断

Assets/Objects/Player/Player.prefab, Assets/Objects/Player/PlayerAction/DivePlayerAction.cs
* close #114
* 吹っ飛ばす力を調整できるようにした。
* 暫定で15にした。（今までの7.5倍）
=> ダイブアクションの吹っ飛ばす力を調整。

Assets/Scenes/ChangeSceneReceiver.cs, Assets/Scenes/PauseController.cs, Assets/Scenes/ResumeReceiver.cs, Assets/Scenes/RetryScene.cs, Assets/Scenes/SceneLoader.cs
* close #123
* シーンを重ねる汎用的な処理を作った
* ゲームオーバー、ゲームクリアシーンの変更
* レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）
=> シーンを重ねる汎用的な処理を作った

Assets/C#/Timer.cs, Assets/Objects/Goal/Goal.cs, Assets/Objects/Player/PlayerCore.cs, Assets/Scenes/GameRoleManager.cs, Assets/Scenes/GameRoleManager.cs.meta, Assets/Scenes/SampleScene.unity
なし
* 急いでいてよく考えたら完成してなかった重ねる処理を完成させた。
* 面倒なのでNoReview
=> 重ねる処理を完成させる

Assets/C#/Score.meta, Assets/C#/Score/ScoreAdder.cs, Assets/C#/Score/ScoreAdder.cs.meta, Assets/C#/Score/ScoreDrawer.cs, Assets/C#/Score/ScoreDrawer.cs.meta, Assets/C#/Score/ScoreManager.cs, Assets/C#/Score/ScoreManager.cs.meta, Assets/Objects/Enemys/DelayDestroy.cs, Assets/Objects/Enemys/TestEnemy.prefab, Assets/Scenes/Manager.unity, Assets/Scenes/SampleScene.unity
* close #117 （マージしたら自動で閉じる場合closeを付ける）
* 撃破数が画面右端に表示されるようになりました
* 特にないです
* 死んだらカウントされるので不慮の事故でペンギンがなくなった際もカウントされます
=> 撃破数を画面右端に追加しました。

Assets/Objects/Enemys/TestEnemyAttacker.cs, Assets/Objects/Enemys/TestEnemySponer.cs
なし
* `Assets/Objects/Enemys/TestEnemySponer.cs`の`sponeAngle`でスポーン時の角度を調整できるようにした。
* `sponeAngle`で指定した方向から90度ずれる問題は敵のモーションを付けるときに直す予定です。
=> スポーン時の角度を調整できるようにした。

Assets/Scenes/GameTitle.unity
=> タイトルシーンを変更

Assets/Scenes/MAP02.unity
=> UIの位置を変更しました

Assets/Objects/Enemys/ShotEnemyTest.meta, Assets/Objects/Enemys/ShotEnemyTest/ShotEnemy.prefab, Assets/Objects/Enemys/ShotEnemyTest/ShotEnemy.prefab.meta, Assets/Objects/Enemys/ShotEnemyTest/ShotEnemyTest.cs, Assets/Objects/Enemys/ShotEnemyTest/ShotEnemyTest.cs.meta, Assets/Objects/Enemys/ShotEnemyTest/bullet.prefab, Assets/Objects/Enemys/ShotEnemyTest/bullet.prefab.meta
* close #142 （マージしたら自動で閉じる場合closeを付ける）
* プレハブにShotEnemyTestを追加
* 
* プレイヤーを向いて弾を撃つ敵をかなり簡易的に実装したので、今後作り直しが必要になるかもです。申し訳ない
=> 弾を撃つ敵をShotEnemyTestとして追加
